pub mod basic;
mod variable;
mod constant;
mod func;
mod data_type;
mod control_flow;
mod ownership;
mod borrowing;
mod struct_demo;
mod enum_demo;
mod match_demo;
mod error_handle;
mod lifestyle;
mod shadowing;